// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PartyTown.Data;

#nullable disable

namespace PartyTown.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513220949_InitPersonaMemory")]
    partial class _20260513220949_InitPersonaMemory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "11.0.0-preview.3.26207.106")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PartyTown.Data.Entities.PersonaMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChatGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_group_id");

                    b.Property<DateTimeOffset>("EncodedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("encoded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.Property<int>("SourceMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("source_message_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_persona_memory");

                    b.HasIndex("PersonaId", "PartyId")
                        .HasDatabaseName("ix_persona_memory_persona_id_party_id");

                    b.HasIndex("PartyId", "ChatGroupId", "SourceMessageId")
                        .HasDatabaseName("ix_persona_memory_party_id_chat_group_id_source_message_id");

                    b.ToTable("persona_memory", "app");
                });
#pragma warning restore 612, 618
        }
    }
}
