namespace PartyTown.Grains.Generation;

[Alias("PartyTown.Grains.Generation.ILlmEndpointGrain")]
public interface ILlmEndpointGrain : IGrainWithIntegerKey
{
    [Alias("GetModelsAsync")]
    Task<IReadOnlyList<LlmModel>> GetModelsAsync(CancellationToken cancellationToken = default);

    [Alias("GenerateStreamAsync")]
    IAsyncEnumerable<LlmGenerationEvent> GenerateAsync(LlmGenerationJob parameters, CancellationToken cancellationToken = default);

    // NOTE: Not sure if this is sufficient info for the router to make a decision
    // But this is how much backpressure (pending generations) the endpoint has
    [Alias("Pressure")]
    ValueTask<int> PressureAsync();
}

[Alias("PartyTown.Grains.Generation.IOllamaEndpointGrain")]
public interface IOllamaEndpointGrain : ILlmEndpointGrain { }

[Alias("PartyTown.Grains.Generation.IOpenRouterEndpointGrain")]
public interface IOpenRouterEndpointGrain : ILlmEndpointGrain { }

[Alias("PartyTown.Grains.Generation.ILlmRouterGrain")]
public interface ILlmRouterGrain : IGrainWithIntegerKey
{
    [Alias("RouteAsync")]
    Task<ILlmEndpointGrain> RouteAsync(
        JobComplexity jobComplexity,
        CancellationToken cancellationToken = default);

    [Alias("GetModelsAsync")]
    Task<IReadOnlyList<LlmModel>> GetModelsAsync(CancellationToken cancellationToken = default);
}

[GenerateSerializer]
[Alias("PartyTown.Grains.Generation.LlmGenerationEvent")]
public readonly record struct LlmGenerationEvent(
    [property: Id(0)] string Type,
    [property: Id(1)] string Data);

[GenerateSerializer]
[Alias("PartyTown.Grains.Generation.LlmChatMessage")]
public sealed record class LlmChatMessage
{
    [Id(0)] public string Role { get; init; } = string.Empty;
    [Id(1)] public string Content { get; init; } = string.Empty;
    [Id(2)] public string? Name { get; init; }
}

/// <summary>
/// Parameters for a LLM generation job to be routed and generated by an LLM.
/// </summary>
[GenerateSerializer]
[Alias("PartyTown.Grains.Generation.LlmGenerationJob")]
public sealed record class LlmGenerationJob
{
    [Id(0)] public IReadOnlyList<LlmChatMessage> Messages { get; init; } = [];
    [Id(1)] public JobComplexity JobComplexity { get; init; }
    [Id(2)] public LlmModelParameters? ModelParameters { get; init; }
    [Id(3)] public Dictionary<string, string>? JobData { get; init; }
    [Id(4)] public string? ResponseFormat { get; init; }
}

/// <summary>
/// Complexity of a LLM generation job. This lets the router know what models
/// it can route the job to.
/// In the future this concept will be exanded to include more specialized types
/// of complexity jobs (e.g. data processing, character adherence, etc.).
/// </summary>
[Flags]
public enum JobComplexity
{
    General = 1,
}

/// <summary>
/// Parameters for an LLM model.
/// </summary>
[GenerateSerializer]
[Alias("PartyTown.Grains.Generation.LlmModelParameters")]
public sealed record class LlmModelParameters
{
    [Id(0)] public double? Temperature { get; init; }
    // Serialized JSON string (JsonObject is not Orleans-serializable)
    [Id(1)] public string? ResponseFormat { get; init; }
}

[GenerateSerializer]
[Alias("PartyTown.Grains.Generation.LlmModel")]
public sealed record class LlmModel
{
    [Id(0)] public required string Name { get; init; }
    [Id(1)] public required int EndpointProviderGrainId { get; init; }
    [Id(2)] public required string ProviderType { get; init; }
    [Id(3)] public string? ProviderDescription { get; init; }
    [Id(4)] public string? Description { get; init; }
    [Id(5)] public int? ContextLength { get; init; }
    [Id(6)] public JobComplexity SupportedComplexities { get; init; }

    internal bool Supports(JobComplexity jobComplexity)
        => SupportedComplexities.HasFlag(jobComplexity);
}
