namespace PartyTown.Grains.Generation;

[Alias("PartyTown.Grains.Generation.ILlmEndpointGrain")]
public interface ILlmEndpointGrain : IGrainWithIntegerKey
{
    /// <summary>
    /// Gets the list of LLM models supported by this endpoint.
    /// </summary>
    /// <returns>The read-only list of models that the endpoint can serve.</returns>
    [Alias("GetModelsAsync")]
    Task<IReadOnlyList<LlmModel>> GetModelsAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Streams generation events produced for the specified generation job.
    /// </summary>
    /// <param name="parameters">The generation job describing input messages, job complexity, optional model parameters, optional job data, and optional response format.</param>
    /// <returns>A sequence of <see cref="LlmGenerationEvent"/> items representing streamed generation output (content chunks, reasoning chunks, and error events) for the requested job.</returns>
    [Alias("GenerateStreamAsync")]
    IAsyncEnumerable<LlmGenerationEvent> GenerateAsync(LlmGenerationJob parameters, CancellationToken cancellationToken = default);

    // NOTE: Not sure if this is sufficient info for the router to make a decision
    /// <summary>
    /// Gets the current backpressure level for the endpoint as the count of pending generation requests.
    /// </summary>
    /// <returns>The number of pending generation requests currently queued for the endpoint.</returns>
    [Alias("Pressure")]
    ValueTask<int> PressureAsync();
}

[Alias("PartyTown.Grains.Generation.IOllamaEndpointGrain")]
public interface IOllamaEndpointGrain : ILlmEndpointGrain { }

[Alias("PartyTown.Grains.Generation.IOpenRouterEndpointGrain")]
public interface IOpenRouterEndpointGrain : ILlmEndpointGrain { }

[Alias("PartyTown.Grains.Generation.ILlmRouterGrain")]
public interface ILlmRouterGrain : IGrainWithIntegerKey
{
    /// <summary>
        /// Selects an endpoint grain appropriate for the specified job complexity.
        /// </summary>
        /// <param name="jobComplexity">The complexity category of the job used to determine a compatible endpoint.</param>
        /// <returns>The endpoint grain chosen to handle jobs of the given complexity.</returns>
        [Alias("RouteAsync")]
    Task<ILlmEndpointGrain> RouteAsync(
        JobComplexity jobComplexity,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets the list of LLM models supported by this endpoint.
    /// </summary>
    /// <returns>The read-only list of models that the endpoint can serve.</returns>
    [Alias("GetModelsAsync")]
    Task<IReadOnlyList<LlmModel>> GetModelsAsync(CancellationToken cancellationToken = default);
}

[GenerateSerializer]
[Alias("PartyTown.Grains.Generation.LlmGenerationEvent")]
public readonly record struct LlmGenerationEvent(
    [property: Id(0)] string Type,
    [property: Id(1)] string Data)
{
    public const string ContentChunk = "message";
    public const string ReasoningChunk = "reasoning";
    public const string GenerationError = "error";
}

[GenerateSerializer]
[Alias("PartyTown.Grains.Generation.LlmChatMessage")]
public sealed record class LlmChatMessage
{
    [Id(0)] public string Role { get; init; } = string.Empty;
    [Id(1)] public string Content { get; init; } = string.Empty;
    [Id(2)] public string? Name { get; init; }
}

/// <summary>
/// Parameters for a LLM generation job to be routed and generated by an LLM.
/// </summary>
[GenerateSerializer]
[Alias("PartyTown.Grains.Generation.LlmGenerationJob")]
public sealed record class LlmGenerationJob
{
    [Id(0)] public IReadOnlyList<LlmChatMessage> Messages { get; init; } = [];
    [Id(1)] public JobComplexity JobComplexity { get; init; }
    [Id(2)] public LlmModelParameters? ModelParameters { get; init; }
    [Id(3)] public Dictionary<string, string>? JobData { get; init; }
    [Id(4)] public string? ResponseFormat { get; init; }
}

/// <summary>
/// Complexity of a LLM generation job. This lets the router know what models
/// it can route the job to.
/// In the future this concept will be exanded to include more specialized types
/// of complexity jobs (e.g. data processing, character adherence, etc.).
/// </summary>
[Flags]
public enum JobComplexity
{
    General = 1,
}

/// <summary>
/// Parameters for an LLM model.
/// </summary>
[GenerateSerializer]
[Alias("PartyTown.Grains.Generation.LlmModelParameters")]
public sealed record class LlmModelParameters
{
    [Id(0)] public double? Temperature { get; init; }
    // Serialized JSON string (JsonObject is not Orleans-serializable)
    [Id(1)] public string? ResponseFormat { get; init; }
}

[GenerateSerializer]
[Alias("PartyTown.Grains.Generation.LlmModel")]
public sealed record class LlmModel
{
    [Id(0)] public required string Name { get; init; }
    [Id(1)] public required int EndpointProviderGrainId { get; init; }
    [Id(2)] public required string ProviderType { get; init; }
    [Id(3)] public string? ProviderDescription { get; init; }
    [Id(4)] public string? Description { get; init; }
    [Id(5)] public int? ContextLength { get; init; }
    [Id(6)] public JobComplexity SupportedComplexities { get; init; }

    /// <summary>
        /// Determines whether the model supports the specified job complexity.
        /// </summary>
        /// <param name="jobComplexity">The job complexity flag to test for support.</param>
        /// <returns>`true` if the model supports the given job complexity, `false` otherwise.</returns>
        internal bool Supports(JobComplexity jobComplexity)
        => SupportedComplexities.HasFlag(jobComplexity);
}
