/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { StanceTargetKind } from './stanceTargetKind';

export interface AppendStanceRequest {
    /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
    valence: number | string;
    /** @nullable */
    reasoning: string | null;
    targetKind: StanceTargetKind;
    /** @nullable */
    targetPersonaId: string | null;
    /** @nullable */
    targetConceptName: string | null;
}
