/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PartyParticipant } from './partyParticipant';

export interface ChatGroupInfo {
    id?: string;
    name?: string;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    createdAt?: number | string;
    /** @nullable */
    scenario?: string | null;
    participants?: PartyParticipant[];
}
