/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ChatGroupInfo {
    id?: string;
    name?: string;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    createdAt?: number | string;
}
