/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ImportedMessageForCommit } from './importedMessageForCommit';
import type { PersonaStubForCommit } from './personaStubForCommit';
import type { UserParticipantStub } from './userParticipantStub';

export interface CommitImportRequest {
    partyId?: string;
    chatGroupName?: string;
    /** @nullable */
    scenario?: string | null;
    personas?: PersonaStubForCommit[];
    messages?: ImportedMessageForCommit[];
    userParticipant?: null | UserParticipantStub;
}
