/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ConsolidationRunResponse {
    runId: string;
    personaId: string;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    recollectionsWalked: number | string;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    stancesAppended: number | string;
    /** @nullable */
    watermark: string | null;
    skipped: boolean;
}
