/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreatePartyRequest {
    partyName?: string;
    /** @nullable */
    userId?: string | null;
    /** @nullable */
    userName?: string | null;
}
