/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface DraftItemEdit {
    /** @nullable */
    routing?: string | null;
    /** @nullable */
    summary?: string | null;
    /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
     */
    weight?: number | string | null;
}
