/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export type DriverKind = (typeof DriverKind)[keyof typeof DriverKind];

export const DriverKind = {
    User: 'User',
    LLM: 'LLM',
    System: 'System',
} as const;
