/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ImportSampleChunk } from './importSampleChunk';

export interface ExtractPersonasRequest {
    systemInstruction?: string;
    /** @nullable */
    sampleChunks?: ImportSampleChunk[] | null;
}
