/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export type GetPartyIdChatGroupsChatGroupIdPapertrailParams = {
    /**
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
    sinceMessageId?: number | string;
    format?: string;
};
