/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ChunkSummary } from './chunkSummary';
import type { ImportScene } from './importScene';
import type { ImportSessionOverviewCategories } from './importSessionOverviewCategories';
import type { ImportSettings } from './importSettings';

export interface ImportSessionOverview {
    id?: string;
    /** @nullable */
    fileName?: string | null;
    createdAt?: string;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    chunkCount?: number | string;
    categories?: ImportSessionOverviewCategories;
    chunks?: ChunkSummary[];
    settings?: ImportSettings;
    scenes?: ImportScene[];
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    draftItemCount?: number | string;
}
