/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ImportDraftItem {
    id?: string;
    sceneId?: string;
    type?: string;
    /** @nullable */
    persona?: string | null;
    summary?: string;
    /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
    weight?: number | string;
    participants?: string[];
    concepts?: string[];
    sourceChunks?: (number | string)[];
    sourceId?: string;
    routing?: string;
    /** @nullable */
    routingReason?: string | null;
    routingOverridden?: boolean;
    at?: string;
    suggestedSummary?: string;
    /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
    suggestedWeight?: number | string;
    suggestedRouting?: string;
}
