/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ImportConcept } from './importConcept';
import type { ImportDraftItem } from './importDraftItem';
import type { PersonaCardDraft } from './personaCardDraft';

export interface ImportDraftView {
    items?: ImportDraftItem[];
    concepts?: ImportConcept[];
    cards?: PersonaCardDraft[];
}
