/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ImportCorrection {
    id?: string;
    sessionId?: string;
    sceneId?: string;
    partyId?: string;
    roomId?: string;
    /** @nullable */
    itemId?: string | null;
    kind?: string;
    chunkRefs?: (number | string)[];
    /** @nullable */
    suggested?: string | null;
    /** @nullable */
    final?: string | null;
    /** @nullable */
    note?: string | null;
    committedAt?: string;
}
