/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ChunkRouting } from './chunkRouting';
import type { ImportLedgerByDisposition } from './importLedgerByDisposition';

export interface ImportLedger {
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    totalChunks?: number | string;
    byDisposition?: ImportLedgerByDisposition;
    reconciles?: boolean;
    chunks?: ChunkRouting[];
}
