/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ImportCommitTarget {
    partyId?: string;
    roomId?: string;
    roomName?: string;
    userParticipantId?: string;
}
