/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ImportScene {
    id?: string;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    fromChunk?: number | string;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    toChunk?: number | string;
    /** @nullable */
    note?: string | null;
    includeDossier?: boolean;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    runCount?: number | string;
    /** @nullable */
    lastRunAt?: string | null;
}
