/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ImportedMessageForCommit {
    /** @nullable */
    senderPlaceholderId?: string | null;
    senderType?: string;
    /** @nullable */
    content?: string | null;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    sendAt?: number | string;
    /** @nullable */
    kind?: string | null;
}
