/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ImportConcept {
    name?: string;
    aliases?: string[];
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    mentions?: number | string;
}
