/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface LlmModel {
    id?: string;
    name?: string;
    provider?: string;
    /** @nullable */
    description?: string | null;
    /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
    contextLength?: number | string | null;
}
