/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { JobComplexity } from './jobComplexity';

export interface LlmModel {
    name: string;
    endpointProviderGrainId: string;
    providerType: string;
    /** @nullable */
    providerDescription?: string | null;
    /** @nullable */
    description?: string | null;
    /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
    contextLength?: number | string | null;
    supportedComplexities?: JobComplexity;
}
