/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { JobComplexity } from './jobComplexity';

export interface LlmProviderEntry {
    id?: string;
    type: string;
    baseUrl: string;
    /** @nullable */
    apiKey?: string | null;
    /** @nullable */
    modelName?: string | null;
    supportedComplexities?: JobComplexity;
    /**
     * @nullable
     * @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$
     */
    generationTimeout?: string | null;
}
