/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface MemoryGraphNode {
    id: string;
    kind: string;
    /** @nullable */
    description?: string | null;
    /** @nullable */
    display?: string | null;
    /** @nullable */
    createdAt?: string | null;
}
