/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PartyInfo } from './partyInfo';
import type { PersonaMetadata } from './personaMetadata';

export interface PartyDetails {
    party: PartyInfo;
    personaParticipants: PersonaMetadata[];
}
