/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DriverKind } from './driverKind';

export interface PartyParticipant {
    id?: string;
    name?: string;
    driver?: DriverKind;
}
