/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DriverKind } from './driverKind';

export interface Persona {
    systemPrompt?: string;
    /** @nullable */
    bio?: string | null;
    /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
    chattiness?: number | string;
    /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
    impulsivity?: number | string;
    id?: string;
    name?: string;
    driver?: DriverKind;
}
