/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface PersonaCardDraft {
    persona?: string;
    systemPrompt?: string;
    /** @nullable */
    bio?: string | null;
    humanEdited?: boolean;
    /** @nullable */
    proposedSystemPrompt?: string | null;
    /** @nullable */
    proposedBio?: string | null;
    traitFingerprint?: string;
    /** @nullable */
    finalizedAt?: string | null;
    /** @nullable */
    committedSystemPrompt?: string | null;
    /** @nullable */
    committedBio?: string | null;
}
