/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface PersonaStubForCommit {
    placeholderId?: string;
    name?: string;
    systemPrompt?: string;
    /** @nullable */
    bio?: string | null;
    isNew?: boolean;
    /** @nullable */
    preExistingId?: string | null;
}
