/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface Persona {
    systemPrompt?: string;
    /** @nullable */
    bio?: string | null;
    id?: string;
    name?: string;
    isUser?: boolean;
}
