/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface PromptRequest {
    chatGroupId?: string;
    prompt?: string;
    model?: string;
    provider?: string;
    /** @nullable */
    personaId?: string | null;
    /** @nullable */
    senderId?: string | null;
    /** @nullable */
    senderName?: string | null;
}
