/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface PromptRequest {
    chatGroupId?: string;
    prompt?: string;
    /** @nullable */
    senderId?: string | null;
}
