/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface RegenerateCharDetailResponse {
    /** @nullable */
    prompt: string | null;
    /** @nullable */
    bio: string | null;
}
