/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface RegenerateCharDetailRequest {
    primaryName?: string;
    /** @nullable */
    names?: string[] | null;
    /** @nullable */
    evidence?: string[] | null;
    /** @nullable */
    archetype?: string | null;
    /** @nullable */
    systemInstructionText?: string | null;
    mode?: string;
}
