/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PersonaCardDraft } from './personaCardDraft';

export interface SceneFinalizeResult {
    cards?: PersonaCardDraft[];
    skipped?: string[];
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    llmCalls?: number | string;
}
