/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ChunkRouting } from './chunkRouting';
import type { DedupDrop } from './dedupDrop';
import type { DegradedRecord } from './degradedRecord';
import type { ImportDraftItem } from './importDraftItem';

export interface SceneRunResult {
    sceneId?: string;
    ranAt?: string;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    llmCalls?: number | string;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    unparseableCalls?: number | string;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    replacedItems?: number | string;
    items?: ImportDraftItem[];
    chunkRoutings?: ChunkRouting[];
    deduped?: DedupDrop[];
    degraded?: DegradedRecord[];
}
