/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface SceneCommitResult {
    sceneId?: string;
    partyId?: string;
    roomId?: string;
    committedAt?: string;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    messagesWritten?: number | string;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    eventsWritten?: number | string;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    recollectionsWritten?: number | string;
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    conceptLinks?: number | string;
    personasMinted?: string[];
    /** @pattern ^-?(?:0|[1-9]\d*)$ */
    correctionsRecorded?: number | string;
    unmatchedParticipants?: string[];
    personasUpdated?: string[];
    personaUpdatesSkipped?: string[];
}
