/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export type StanceOrigin = (typeof StanceOrigin)[keyof typeof StanceOrigin];

export const StanceOrigin = {
    Curator: 'Curator',
    Consolidation: 'Consolidation',
    Retract: 'Retract',
} as const;
