/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { StanceOrigin } from './stanceOrigin';
import type { StanceTargetKind } from './stanceTargetKind';

export interface StanceRecord {
    id: string;
    /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
    valence: number | string;
    reasoning: string;
    ts: string;
    targetKind: StanceTargetKind;
    /** @nullable */
    targetPersonaId: string | null;
    /** @nullable */
    targetConceptName: string | null;
    /** @nullable */
    targetConceptDisplay: string | null;
    isCurrent: boolean;
    origin?: StanceOrigin;
    /** @nullable */
    runId?: string | null;
    /** @nullable */
    retractsId?: string | null;
    isIntrinsic?: boolean;
}
