/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DriverOverrideEntry } from './driverOverrideEntry';

export interface UpdateChatGroupDriverOverridesRequest {
    overrides?: DriverOverrideEntry[];
}
