namespace PartyTown.Model;

/// <summary>
/// A single message in a party's conversation history.
/// Persisted by <see cref="PartyGrain"/> and sent to clients via realtime hub.
/// </summary>
[GenerateSerializer, Alias(nameof(ChatMessage))]
public record class ChatMessage
{
    /// <summary>Unique identifier for this message within the party.</summary>
    [Id(0)]
    public int MessageId { get; set; }

    /// <summary>The actual message text content.</summary>
    [Id(1)]
    public string? Content { get; set; }

    /// <summary>Reasoning output from models that support it (e.g., o1).</summary>
    [Id(2)]
    public string? Reasoning { get; set; }

    /// <summary>Overseer decision JSON if this message was generated by the automatic continuation flow.</summary>
    [Id(3)]
    public string? Overseer { get; set; }

    /// <summary>Error message if generation failed.</summary>
    [Id(4)]
    public string? Error { get; set; }

    /// <summary>Sender type: "user" or "assistant".</summary>
    [Id(5)]
    public string SenderType { get; set; } = "assistant";

    /// <summary>ID of the persona or user who sent this message.</summary>
    [Id(6)]
    public Guid SenderId { get; set; }

    /// <summary>Unix timestamp in milliseconds when the message was sent/completed.</summary>
    [Id(7)]
    public long? SendAt { get; set; }

    /// <summary>Identifier of the chat group this message belongs to.</summary>
    [Id(9)]
    public Guid ChatGroupId { get; set; }
}
